// <auto-generated />
using System;
using Coffer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Coffer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260226150359_AddAmount")]
    partial class AddAmount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("AppUserLedger", b =>
                {
                    b.Property<Guid>("MemberOfId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MembersId")
                        .HasColumnType("TEXT");

                    b.HasKey("MemberOfId", "MembersId");

                    b.HasIndex("MembersId");

                    b.ToTable("AppUserLedger");
                });

            modelBuilder.Entity("Coffer.Data.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Coffer.Models.Cost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Added")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddedById")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrencyISONum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LedgerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PayedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddedById");

                    b.HasIndex("CurrencyISONum");

                    b.HasIndex("LedgerId");

                    b.HasIndex("PayedById");

                    b.ToTable("Costs");
                });

            modelBuilder.Entity("Coffer.Models.Currency", b =>
                {
                    b.Property<int>("ISONum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Decimals")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISOName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ISONum");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Coffer.Models.IOU", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrencyISONum")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LedgerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwedToUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Settled")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SettledAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyISONum");

                    b.HasIndex("LedgerId");

                    b.HasIndex("OwedByUserId");

                    b.HasIndex("OwedToUserId");

                    b.ToTable("IOUs");
                });

            modelBuilder.Entity("Coffer.Models.Ledger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultCurrencyISONum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultShareType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefaultCurrencyISONum");

                    b.HasIndex("OwnerId");

                    b.ToTable("Ledgers");
                });

            modelBuilder.Entity("Coffer.Models.Share", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrencyISONum")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LedgerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SingleCostId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Size")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyISONum");

                    b.HasIndex("LedgerId");

                    b.HasIndex("SingleCostId");

                    b.HasIndex("UserId");

                    b.ToTable("Shares");
                });

            modelBuilder.Entity("Coffer.Models.Stake", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountStaked")
                        .HasColumnType("TEXT");

                    b.Property<string>("HolderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LedgerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HolderId");

                    b.HasIndex("LedgerId");

                    b.ToTable("Stakes");
                });

            modelBuilder.Entity("Coffer.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LedgerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LedgerId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("CostTag", b =>
                {
                    b.Property<Guid>("CostsId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CostsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("CostTag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ShareTag", b =>
                {
                    b.Property<int>("IncludeTagsId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IncludedSharesId")
                        .HasColumnType("TEXT");

                    b.HasKey("IncludeTagsId", "IncludedSharesId");

                    b.HasIndex("IncludedSharesId");

                    b.ToTable("ShareTag");
                });

            modelBuilder.Entity("ShareTag1", b =>
                {
                    b.Property<int>("ExcludeTagsId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ExcludedSharesId")
                        .HasColumnType("TEXT");

                    b.HasKey("ExcludeTagsId", "ExcludedSharesId");

                    b.HasIndex("ExcludedSharesId");

                    b.ToTable("ShareTag1");
                });

            modelBuilder.Entity("AppUserLedger", b =>
                {
                    b.HasOne("Coffer.Models.Ledger", null)
                        .WithMany()
                        .HasForeignKey("MemberOfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coffer.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Coffer.Models.Cost", b =>
                {
                    b.HasOne("Coffer.Data.AppUser", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Coffer.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyISONum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coffer.Models.Ledger", null)
                        .WithMany("Costs")
                        .HasForeignKey("LedgerId");

                    b.HasOne("Coffer.Data.AppUser", "PayedBy")
                        .WithMany()
                        .HasForeignKey("PayedById");

                    b.Navigation("AddedBy");

                    b.Navigation("Currency");

                    b.Navigation("PayedBy");
                });

            modelBuilder.Entity("Coffer.Models.IOU", b =>
                {
                    b.HasOne("Coffer.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyISONum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coffer.Models.Ledger", null)
                        .WithMany("IOUs")
                        .HasForeignKey("LedgerId");

                    b.HasOne("Coffer.Data.AppUser", "OwedByUser")
                        .WithMany()
                        .HasForeignKey("OwedByUserId");

                    b.HasOne("Coffer.Data.AppUser", "OwedToUser")
                        .WithMany()
                        .HasForeignKey("OwedToUserId");

                    b.Navigation("Currency");

                    b.Navigation("OwedByUser");

                    b.Navigation("OwedToUser");
                });

            modelBuilder.Entity("Coffer.Models.Ledger", b =>
                {
                    b.HasOne("Coffer.Models.Currency", "DefaultCurrency")
                        .WithMany()
                        .HasForeignKey("DefaultCurrencyISONum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coffer.Data.AppUser", "Owner")
                        .WithMany("LedgersOwned")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultCurrency");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Coffer.Models.Share", b =>
                {
                    b.HasOne("Coffer.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyISONum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coffer.Models.Ledger", null)
                        .WithMany("Shares")
                        .HasForeignKey("LedgerId");

                    b.HasOne("Coffer.Models.Cost", "SingleCost")
                        .WithMany()
                        .HasForeignKey("SingleCostId");

                    b.HasOne("Coffer.Data.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Currency");

                    b.Navigation("SingleCost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Coffer.Models.Stake", b =>
                {
                    b.HasOne("Coffer.Data.AppUser", "Holder")
                        .WithMany()
                        .HasForeignKey("HolderId");

                    b.HasOne("Coffer.Models.Ledger", null)
                        .WithMany("Stakes")
                        .HasForeignKey("LedgerId");

                    b.Navigation("Holder");
                });

            modelBuilder.Entity("Coffer.Models.Tag", b =>
                {
                    b.HasOne("Coffer.Models.Ledger", null)
                        .WithMany("AllTags")
                        .HasForeignKey("LedgerId");
                });

            modelBuilder.Entity("CostTag", b =>
                {
                    b.HasOne("Coffer.Models.Cost", null)
                        .WithMany()
                        .HasForeignKey("CostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coffer.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Coffer.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Coffer.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coffer.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Coffer.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShareTag", b =>
                {
                    b.HasOne("Coffer.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("IncludeTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coffer.Models.Share", null)
                        .WithMany()
                        .HasForeignKey("IncludedSharesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShareTag1", b =>
                {
                    b.HasOne("Coffer.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("ExcludeTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coffer.Models.Share", null)
                        .WithMany()
                        .HasForeignKey("ExcludedSharesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Coffer.Data.AppUser", b =>
                {
                    b.Navigation("LedgersOwned");
                });

            modelBuilder.Entity("Coffer.Models.Ledger", b =>
                {
                    b.Navigation("AllTags");

                    b.Navigation("Costs");

                    b.Navigation("IOUs");

                    b.Navigation("Shares");

                    b.Navigation("Stakes");
                });
#pragma warning restore 612, 618
        }
    }
}
